<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Sign Out_icon-connect-signout</name>
   <tag></tag>
   <elementGuidId>4a3b1245-8a8a-4681-823b-670d9c3040be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.icon-connect-signout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='signoutPrimary']/a/div/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>7226a210-2a17-4938-85a5-742a6ea93b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-connect-signout</value>
      <webElementGuid>b9b5e07a-64f9-436b-8aa8-a0895834118e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signoutPrimary&quot;)/a[1]/div[1]/em[@class=&quot;icon-connect-signout&quot;]</value>
      <webElementGuid>e7eb2b0f-c1b7-4e24-9ba6-2b7930270c51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signoutPrimary']/a/div/em</value>
      <webElementGuid>d71bc7ae-a9c4-4516-9949-47420942d7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/div/em</value>
      <webElementGuid>3959df46-2b72-470f-89f6-1147cd63dc84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
