<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Town Or City_TownOrCity</name>
   <tag></tag>
   <elementGuidId>f68c143b-e30d-400e-ac8e-212b6c1aa1b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TownOrCity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TownOrCity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4657f4c6-bff3-4843-b252-5f61346bcdf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control select-boxPrimary ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>7efa964f-a9f4-4095-99d8-9b7ddb802adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>townOrCity</value>
      <webElementGuid>8a1638ad-ebf9-4fa3-8ce7-8031310a2ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TownOrCity</value>
      <webElementGuid>91ed2afc-f9f2-41eb-a014-bae74ed317bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>towns</value>
      <webElementGuid>de9414a3-da2f-4b83-b4b1-d289cbc36b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TownOrCity</value>
      <webElementGuid>d0aef6da-d76a-4513-9af7-2cda65ee347e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TownOrCity&quot;)</value>
      <webElementGuid>6d980036-9ad3-4250-b84a-0cab01764938</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TownOrCity']</value>
      <webElementGuid>cd3f1660-2db4-4067-881e-e4423a6760c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/locationlist/div/div[5]/div[2]/locationdetail/div/form/div[2]/input</value>
      <webElementGuid>b2daaa0d-63c4-426f-a7f4-af4741fa7e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4d2b6ecf-40ee-4688-b89e-c71a45720be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TownOrCity' and @name = 'TownOrCity']</value>
      <webElementGuid>0321a593-d2f3-4651-8408-3f9dd19bae9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
