<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Locations</name>
   <tag></tag>
   <elementGuidId>1aa1c798-8f94-429e-a306-af7f96293498</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#locations > div > span.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='locations']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b3e56b44-61aa-4f5a-93f4-63621bb452a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>7acda604-8cd4-417c-83ca-6022f473f7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Locations</value>
      <webElementGuid>6714eade-7f02-4782-8347-4d74a1ac6c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locations&quot;)/div[1]/span[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>3c20edd6-dd13-4c80-9aa1-490d36e5eb70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='locations']/div/span</value>
      <webElementGuid>7efb2f1b-d6d1-4d48-a311-120c60d948dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rooms &amp; Screens'])[1]/following::span[1]</value>
      <webElementGuid>0d2b2237-af0c-441e-a13a-9cdfcb3ac42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon exchnage'])[1]/following::span[4]</value>
      <webElementGuid>be2d29ef-c14d-4385-851b-ffc5162b2630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/preceding::span[1]</value>
      <webElementGuid>e593325f-51cf-46ee-b5e0-a090e262e650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Access'])[1]/preceding::span[2]</value>
      <webElementGuid>f16104f3-20c3-4aab-b100-75f43b687d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Locations']/parent::*</value>
      <webElementGuid>c8e75fc9-dfb9-45d3-b89c-03aeaaf4eba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/span</value>
      <webElementGuid>d326530d-290d-4316-b24a-2e7c96e503fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Locations' or . = 'Locations')]</value>
      <webElementGuid>194252d5-d335-4636-a593-86681f9e0c9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
