<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Device Hub</name>
   <tag></tag>
   <elementGuidId>6d06b473-7439-409a-87de-4d1edf250dd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.h2Style</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login']/login/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>968dbc9a-92c7-4c1b-a05c-21b988f3a9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h2Style</value>
      <webElementGuid>0eb7d594-f6d5-4c1c-8a46-8d97d610a79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Device Hub</value>
      <webElementGuid>2498123b-e117-4d8b-9ed7-a4836e51ee3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/login[1]/div[1]/div[@class=&quot;h2Style&quot;]</value>
      <webElementGuid>d5106ec3-8944-47ab-ae23-68c30557b498</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/login/div/div</value>
      <webElementGuid>20ca8a10-370f-4bd4-a04e-6c2fde698ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::div[2]</value>
      <webElementGuid>d1338efd-dbc1-4243-886e-e6a787c1186c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Device Hub']/parent::*</value>
      <webElementGuid>d6bca637-74e4-4560-a70b-bc5c01c1259b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>1c51d923-2c24-495e-a6c5-4cb4a5983475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Device Hub' or . = 'Device Hub')]</value>
      <webElementGuid>fe2b653a-3a2f-43d6-be08-69b678d3b5af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
