<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Device Hub_condeco-logo</name>
   <tag></tag>
   <elementGuidId>3445e265-7ae4-4092-8b37-45583d4d0c06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#condeco-logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='condeco-logo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bd2ebff8-3879-4b06-b9ab-2d491fe6557a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>condeco-logo</value>
      <webElementGuid>78f72916-66e3-401b-9e63-f4666fb2c2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/Condeco_Eptura_logo@3x.png</value>
      <webElementGuid>6e351f6f-1c44-40c7-9635-e5fbb0fcb7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;condeco-logo&quot;)</value>
      <webElementGuid>9fab0682-47db-4a4a-a540-d9b50ddb4d19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='condeco-logo']</value>
      <webElementGuid>3c6392cb-ada4-40f2-b4e0-4447c7bbb674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/login/div/img</value>
      <webElementGuid>f626fb39-f3ef-462f-9ba6-be8c84780e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>babe9790-6972-4c48-b23c-04034ad871dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'condeco-logo' and @src = 'assets/Condeco_Eptura_logo@3x.png']</value>
      <webElementGuid>8811a98f-650f-4d40-a2ff-f77802d3443a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
