<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Show all</name>
   <tag></tag>
   <elementGuidId>d4641204-c884-48b8-b5bb-c0e7a460c509</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#showAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='showAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c9eb5bee-839b-4370-bbe3-2a6c455fc65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default pull-right btn-show</value>
      <webElementGuid>77144441-4c0c-4ce3-b6a5-74e7c19b38ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showAll</value>
      <webElementGuid>7cbc7622-5463-4169-91fa-e5954017ff69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show all</value>
      <webElementGuid>d9771d36-fce6-437e-929f-40a242e31a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show all</value>
      <webElementGuid>2d5773f9-bfa4-4f86-8ea5-e4015f5ceb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showAll&quot;)</value>
      <webElementGuid>932727c8-3e8d-41c6-9dd5-315e1822a5c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='showAll']</value>
      <webElementGuid>98d7925e-e28d-4544-b7ed-12208012bda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/screenthemes/div/div[3]/div[4]/div/div[2]/div[3]/a</value>
      <webElementGuid>e3505be0-7426-4e21-a45e-d7996d98f1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Show all')]</value>
      <webElementGuid>9b370256-bf91-4bf8-bc91-117da8392400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show next 8'])[1]/following::a[1]</value>
      <webElementGuid>addaf420-ba93-4b20-ad3c-cd298f51e04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show less'])[1]/following::a[2]</value>
      <webElementGuid>1108549c-7f16-4746-89c8-a98d52edd8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country-level Themes'])[1]/preceding::a[1]</value>
      <webElementGuid>6814aac6-b952-4885-8c38-80bcf0adb90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add country theme'])[1]/preceding::a[1]</value>
      <webElementGuid>e530f4bc-cd49-42be-a2d4-c33cad319ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Show all']/parent::*</value>
      <webElementGuid>f47ae62f-6537-4eb9-a238-7eb09e40c8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>e03a2836-0163-4022-8058-b9f5d052f48b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'showAll' and (text() = 'Show all' or . = 'Show all')]</value>
      <webElementGuid>84186968-974a-4081-b642-a30c00816ded</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
