<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Screen Themes_icon-connect-themes</name>
   <tag></tag>
   <elementGuidId>7fefd27e-5a64-494d-a5d2-386fd030c421</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.icon-connect-themes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='themes']/div/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>3283ad72-1638-4cba-85be-a64d55838159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-connect-themes</value>
      <webElementGuid>314dd410-81b5-417a-8ac8-e5c0af4183b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;themes&quot;)/div[1]/em[@class=&quot;icon-connect-themes&quot;]</value>
      <webElementGuid>a17d081f-f20b-45d9-b395-2e47e9339c86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='themes']/div/em</value>
      <webElementGuid>129f119a-5ff6-4356-b455-23404391d18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/div/em</value>
      <webElementGuid>eaf90e4c-4b57-45da-adce-d0597b847636</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
