<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose a theme name_themeName</name>
   <tag></tag>
   <elementGuidId>0a288ffd-b697-4990-885f-d099f99ab249</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#themeName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='themeName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a321f28-5d15-4eff-a60d-3f0229a9b99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>e67526d0-8274-43e1-8b72-b61a66f7d784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>themeName</value>
      <webElementGuid>d6b6ab70-2917-4ed6-87a4-a003b278735e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>themeName</value>
      <webElementGuid>99df62b7-50b8-46a3-9b47-cb2cae861ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>themeName</value>
      <webElementGuid>190b9d1c-6d10-43d5-b73c-569e81c88cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;themeName&quot;)</value>
      <webElementGuid>78e8a7dd-7656-4097-ae22-b03a225ad0cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='themeName']</value>
      <webElementGuid>a5c38056-13a7-4c0e-943d-c755a8d3f4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div/div[2]/div/input</value>
      <webElementGuid>b0bc4294-3295-4c5c-95cf-f49731ffe66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/input</value>
      <webElementGuid>7bef3b94-6743-43bc-ae32-0692f33ace1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'themeName' and @name = 'themeName']</value>
      <webElementGuid>a163f9a4-fd8f-4b18-ad31-79733eeba3fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
