<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Default Theme(1)_contextHolder</name>
   <tag></tag>
   <elementGuidId>4ec012bc-ab2a-4be0-859c-01c5a4ae46ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='contextHolder'])[114]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c79a5cc7-822b-4bae-8651-da411cc4c523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-option-horizontal</value>
      <webElementGuid>63921bc8-aa34-4778-8373-08f380922169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contextHolder</value>
      <webElementGuid>6274a6a0-3271-405e-9f02-bfe1480f09a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)/screenthemes[1]/div[@class=&quot;pageAnimation&quot;]/div[@class=&quot;panel-default&quot;]/div[@class=&quot;row is-flex&quot;]/div[@class=&quot;col-lg-3 col-padding width-Theme&quot;]/div[@class=&quot;panel panel-default panel-card width-Themes&quot;]/div[@class=&quot;panel-body panel-card-body&quot;]/span[@id=&quot;contextHolder&quot;]</value>
      <webElementGuid>bf9bc395-e381-4119-8b89-f6ec5c062d72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='contextHolder'])[114]</value>
      <webElementGuid>47256d4d-41e0-4d84-875e-59cc9c2e9a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/screenthemes/div/div[3]/div[3]/div[114]/div/div/span</value>
      <webElementGuid>2ee62068-6a1a-4241-a7c4-dff09d71cdb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[114]/div/div/span</value>
      <webElementGuid>51e8d3e6-fe7b-4209-ba17-61afe7ee1776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'contextHolder']</value>
      <webElementGuid>68b7634d-f3af-47c0-9768-2329ff5296bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
