<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add user</name>
   <tag></tag>
   <elementGuidId>979b163f-d701-4879-9e85-d163c6ea3053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addNewUser</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addNewUser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>37841c3c-5b14-430d-8c3a-ae7b8948ec05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-button btn btn-default pull-right</value>
      <webElementGuid>bb900be9-ec13-409c-8351-ae1d0c397dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addNewUser</value>
      <webElementGuid>f0c4c9ec-35c0-4839-b3f8-5c9c9166ffc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add new</value>
      <webElementGuid>16e414d0-f299-45bf-99b7-125b6e9407e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add user</value>
      <webElementGuid>589bfcc9-6be2-4916-bc43-69aa1f1055aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addNewUser&quot;)</value>
      <webElementGuid>80db8cb1-34c3-4413-af6f-2bb28fc9bef8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addNewUser']</value>
      <webElementGuid>56526629-044d-420b-8e44-93bc35857686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/users/div/div[2]/div/div/div[2]/a[2]</value>
      <webElementGuid>e791f5dd-08ee-4720-9508-0b478fd891af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add user')]</value>
      <webElementGuid>be502f03-8c03-4728-9459-e71ca146ec92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download user data'])[1]/following::a[1]</value>
      <webElementGuid>e4aa33d9-688c-473e-a984-44a35ed32a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download sample CSV file'])[1]/following::a[2]</value>
      <webElementGuid>2c9d774a-b44b-4adb-9d60-866be0d2c3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulk upload'])[1]/preceding::a[1]</value>
      <webElementGuid>9ac2b381-9d13-4dc4-8a1c-63d971f91dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show'])[1]/preceding::a[2]</value>
      <webElementGuid>382cefe5-f2a0-4272-8df2-00348776a334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add user']/parent::*</value>
      <webElementGuid>8adc9137-3068-4f1d-8178-c4438171a27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>e4d156d8-8f8c-4222-b9c2-65539ca186b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'addNewUser' and (text() = 'Add user' or . = 'Add user')]</value>
      <webElementGuid>a461f3a2-0c4c-4f69-8162-a40aaa136801</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
