<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Sign Out_icon-connect-signout</name>
   <tag></tag>
   <elementGuidId>dc49b7cb-1b6b-4580-8b3b-5fbc9e976404</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.icon-connect-signout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='signoutPrimary']/a/div/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>6f21ca8c-5eb6-43cf-bb58-3bee8710a617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-connect-signout</value>
      <webElementGuid>63483234-27f9-4709-9da8-f916b265b63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signoutPrimary&quot;)/a[1]/div[1]/em[@class=&quot;icon-connect-signout&quot;]</value>
      <webElementGuid>af2ab446-8ab9-4f6e-831e-41092cbc02b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signoutPrimary']/a/div/em</value>
      <webElementGuid>1c85d483-c67f-457a-b246-71057163e596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/div/em</value>
      <webElementGuid>117246a7-cd5b-4d00-b2f0-1ff2d52a8d2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
