<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Users_icon-connect-users</name>
   <tag></tag>
   <elementGuidId>0d317a92-8f41-4506-ad55-645957543457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.icon-connect-users</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='users']/div/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>15a4a2c6-53f7-45b4-a8b7-12e6e217a48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-connect-users</value>
      <webElementGuid>bcf501fc-ba2f-4ac4-821e-c53b9a7e5f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;users&quot;)/div[1]/em[@class=&quot;icon-connect-users&quot;]</value>
      <webElementGuid>24491a9c-15a6-4139-8b48-1ae438c5250a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='users']/div/em</value>
      <webElementGuid>c81e9869-e062-48b4-b4fb-e52e004366e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div/em</value>
      <webElementGuid>838adba7-da20-4fb4-b520-954cafd082c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
