<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile phone number_mobilePhoneNumber</name>
   <tag></tag>
   <elementGuidId>7d95fb3c-6ad1-4363-992a-66afc3a4c239</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobilePhoneNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mobilePhoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed4c75f9-c671-4779-ab3a-d987e61a6e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>098e47c8-7bfe-4a9d-9edd-1c9f7cd9db35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>mobilePhoneNumber</value>
      <webElementGuid>a503f680-48d9-44a7-aee1-661ace4d8591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobilePhoneNumber</value>
      <webElementGuid>cd2098a1-6eb2-41e5-b122-459ca072aafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobilePhoneNumber</value>
      <webElementGuid>b0e8d167-f7e0-4daa-9035-9e25991a9440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobilePhoneNumber&quot;)</value>
      <webElementGuid>99ca047f-a3a7-4537-bde0-5209070607c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mobilePhoneNumber']</value>
      <webElementGuid>0ff62d4a-8645-4492-b677-553e2c642b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/users/div/div[5]/div[2]/userdetail/div/form/div[4]/input</value>
      <webElementGuid>b8366b2e-a2bc-4b14-b47d-cdd3c33451b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>01be8fb2-84bf-4c42-b356-7e66c92e11cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mobilePhoneNumber' and @name = 'mobilePhoneNumber']</value>
      <webElementGuid>69e5f503-094f-446e-84b3-c696751427c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
