<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add user</name>
   <tag></tag>
   <elementGuidId>83b3892e-cb50-4bb4-99c2-4822a83634bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addNewUser</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addNewUser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ceab0d1-8c0c-4a5a-bf8a-beb584635d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-button btn btn-default pull-right</value>
      <webElementGuid>91384913-9293-46bc-b858-09362e15463b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addNewUser</value>
      <webElementGuid>129560a9-2c9a-4ed1-9e71-ab197944440f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add new</value>
      <webElementGuid>5e5e1259-536c-4d96-b3c6-4e4fad351caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add user</value>
      <webElementGuid>65ff7b1a-5148-4fb8-8b56-f64e783aff95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addNewUser&quot;)</value>
      <webElementGuid>9d45a374-7d24-460a-8137-2128272c6f8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addNewUser']</value>
      <webElementGuid>4625d3d3-975e-41b4-8267-006e7813e8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/users/div/div[2]/div/div/div[2]/a[2]</value>
      <webElementGuid>91d026ef-e73b-467a-bdd6-60a3e31086c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add user')]</value>
      <webElementGuid>2a0590e1-1075-46b5-8d11-ebe39baf2b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download user data'])[1]/following::a[1]</value>
      <webElementGuid>397501a4-ef81-433c-90f7-906363d00b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download sample CSV file'])[1]/following::a[2]</value>
      <webElementGuid>460c5680-d27b-43c6-ba3b-fd362e299cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulk upload'])[1]/preceding::a[1]</value>
      <webElementGuid>0f6d71f5-4def-4e22-9e67-e28cc2faa996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show'])[1]/preceding::a[2]</value>
      <webElementGuid>4cf17020-64cc-4e0d-9a4e-41fb9593c850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add user']/parent::*</value>
      <webElementGuid>3ec90d7d-9e86-49e4-93af-b139f43ee904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>abd22485-5191-4f5a-893b-718962ac4f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'addNewUser' and (text() = 'Add user' or . = 'Add user')]</value>
      <webElementGuid>ef47aa3e-2c3b-47cc-85a0-755f5f265737</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
