<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>7c1b79ef-a782-4614-a5b5-39b90d30248a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#users > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='users']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1d01e341-a927-4e8a-95e0-8410ae5db07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;users&quot;)/div[1]</value>
      <webElementGuid>7eb73b0d-9ddf-4495-90c9-52114a7298e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='users']/div</value>
      <webElementGuid>cd72e6e2-6823-4933-a724-27ab406795c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/preceding::div[2]</value>
      <webElementGuid>b75db04b-e231-47bc-b3b1-b9d91f976511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office 365'])[1]/preceding::div[9]</value>
      <webElementGuid>54507053-fe1a-401e-968d-9f800ac8e59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div</value>
      <webElementGuid>ff6a4884-f005-49be-a991-7ce93c90d0af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
