<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Active</name>
   <tag></tag>
   <elementGuidId>510ca823-6403-42d7-b5b8-44fcf991eb0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.custom-radio.statusdiv > label.radioButtonLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content-wrapper']/users/div/div[5]/div[2]/userdetail/div/form/div[6]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>10514651-7224-4c4a-a610-3aa91f3637b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radioButtonLabel</value>
      <webElementGuid>0024cb6a-f04f-4041-b035-4ae274964307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>userStatusActive</value>
      <webElementGuid>375442c0-b7f3-46b7-a46d-5dd31fa057d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>cdecb523-966c-42e5-9588-3b9822249ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)/users[1]/div[@class=&quot;pageAnimation&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/userdetail[1]/div[@class=&quot;pageAnimation&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;statusSpacing&quot;]/div[@class=&quot;custom-radio statusdiv&quot;]/label[@class=&quot;radioButtonLabel&quot;]</value>
      <webElementGuid>fe700cba-511b-43ac-b72b-1708e49fc608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/users/div/div[5]/div[2]/userdetail/div/form/div[6]/div/div/label</value>
      <webElementGuid>8b9c2a70-a8da-4ed7-b621-da40e8b11119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::label[1]</value>
      <webElementGuid>537b050b-1dea-49e1-a514-26b6bbc712c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[10]/following::label[2]</value>
      <webElementGuid>f0dd2ea4-8768-4d93-97af-7ee6e777bb00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disabled'])[2]/preceding::label[1]</value>
      <webElementGuid>04e49c72-9245-4fef-94e2-2cff0493a852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::label[2]</value>
      <webElementGuid>0a616851-48d7-47ab-a8ed-ee391000203d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/label</value>
      <webElementGuid>61969be1-b024-48d1-bea1-ea5a687bb7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Active' or . = 'Active')]</value>
      <webElementGuid>84fde599-ca76-4cf5-af6f-6951f551da25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
