<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_niharikaatesting4666katalon.com</name>
   <tag></tag>
   <elementGuidId>9838e401-a665-45fc-b5a7-abdd14f7f4d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='userList']/tbody/tr[2]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c6cd1245-da07-4acb-b2d6-b38e8226cded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>niharikaatesting4666@katalon.com</value>
      <webElementGuid>88e3f14c-89fc-4567-94b1-14107f77937b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userList&quot;)/tbody[1]/tr[2]/td[3]</value>
      <webElementGuid>354ca650-bb8d-4902-83ea-bdc5ffa0d577</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='userList']/tbody/tr[2]/td[3]</value>
      <webElementGuid>e169e128-994a-43c7-9a24-351e70df8936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='niharika46669'])[1]/following::td[1]</value>
      <webElementGuid>4fb8f2f9-1b68-4961-bc00-b17efd9a7bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalonn'])[1]/following::td[2]</value>
      <webElementGuid>ec7a2bf5-443c-4d44-90ae-5c1818e8e677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[2]/preceding::td[1]</value>
      <webElementGuid>80e60c9f-6781-4e65-a53e-8b022f0ba902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/preceding::td[2]</value>
      <webElementGuid>d6b1bb7d-9e3b-422d-9380-ed3713d4f02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='niharikaatesting4666@katalon.com']/parent::*</value>
      <webElementGuid>401ee9fe-bf26-494b-bda9-d1b77d3c7d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]</value>
      <webElementGuid>b0deb46a-93dc-48f5-87d8-7cc9f13f6ff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'niharikaatesting4666@katalon.com' or . = 'niharikaatesting4666@katalon.com')]</value>
      <webElementGuid>1e9ed709-942a-4cbd-8e15-efbe13d9d5b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
