<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Room Mailbox_mailbox</name>
   <tag></tag>
   <elementGuidId>6f3e1b82-77f9-439f-821f-ac79c2f3b711</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mailbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mailbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c977511-cdeb-405b-aad6-4506e8d3de08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>88256478-7b9a-4d67-aaf0-e3ed3f06a06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>mailbox</value>
      <webElementGuid>d1b0bd1c-c14b-48e3-9a1f-8a4b4218cc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mailbox</value>
      <webElementGuid>b8a5637f-ad9d-4426-8318-dbecfa4a19fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mailbox</value>
      <webElementGuid>0703a967-929c-4a74-bfb0-1f71f8faff85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter the mailbox details.</value>
      <webElementGuid>6ec72ec6-e0c5-45cb-b600-1bee20d69058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mailbox&quot;)</value>
      <webElementGuid>61c718f5-e26a-4181-8972-78970f932c56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mailbox']</value>
      <webElementGuid>aff7bf3b-21fd-4598-ac42-1140fa753db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/rooms/div/div[2]/div[4]/roomdetail/div/form/div[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>2e89d33b-8991-4463-b0e1-3e05ca514857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>375ee4fa-e55c-49dc-91da-a610dc913c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mailbox' and @name = 'mailbox' and @placeholder = 'Please enter the mailbox details.']</value>
      <webElementGuid>8a884e22-7873-4ea9-907f-41ac7a573cb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
