<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Capacity_capacity</name>
   <tag></tag>
   <elementGuidId>b4c49a4d-95da-4af8-9a54-ebac6c104c9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#capacity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='capacity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>592cf328-dc1b-48cd-a993-26bc35fe2806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-dirty ng-invalid</value>
      <webElementGuid>28e62b5c-6e2b-4159-8573-bbe2f619c75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>capacity</value>
      <webElementGuid>5d479856-ffca-4b12-8360-93dca23d759e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>capacity</value>
      <webElementGuid>7af38fa0-6f61-48b1-96f0-044d9f152510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>capacity</value>
      <webElementGuid>5460f10a-17bf-48b6-bb25-a550d92f8755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>dcf36154-8457-43ec-9203-2a6e9e3a031f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter a number</value>
      <webElementGuid>9c0264e5-2c58-4240-af17-fffc2b2ef674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;capacity&quot;)</value>
      <webElementGuid>f4c9e2e1-ef34-44ab-8050-7203bb88c306</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='capacity']</value>
      <webElementGuid>91df699b-7f9a-4f42-9089-b8c738d19481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/rooms/div/div[2]/div[4]/roomdetail/div/form/div[2]/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>087769a5-2558-4c0e-a566-fc69ece58718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>5cd1d9e8-6b59-4b30-ba46-694fd3479d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'capacity' and @name = 'capacity' and @type = 'number' and @placeholder = 'Please enter a number']</value>
      <webElementGuid>e5b5692c-6a0e-43fb-a7c4-3225b12c8119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
