<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Town Or City_TownOrCity</name>
   <tag></tag>
   <elementGuidId>ed3c4a33-e4ec-48d3-93f7-f692069b389d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TownOrCity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TownOrCity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>675e7e08-1f84-42b1-9519-309980a9e78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control select-boxPrimary ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>ebbe80c3-0af4-4ddd-a314-324150fc0521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>townOrCity</value>
      <webElementGuid>5b7309a0-5160-4712-8d85-ffa7dbd75980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TownOrCity</value>
      <webElementGuid>1418dacb-c80b-481a-879a-623e89dc1cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>towns</value>
      <webElementGuid>c069a3dd-74be-4388-95d1-73f1a03f00c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TownOrCity</value>
      <webElementGuid>0731c77a-9182-42d6-8362-ff9d75668a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TownOrCity&quot;)</value>
      <webElementGuid>34486526-7fde-4b21-8118-5ac40bcf382d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TownOrCity']</value>
      <webElementGuid>08748087-efd0-4e6d-844c-36b8c93c6dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/locationlist/div/div[5]/div[2]/locationdetail/div/form/div[2]/input</value>
      <webElementGuid>e0b0a826-9302-4f0b-b3fe-eb34b588fb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>23c1664c-5b24-4315-8334-f8c433d93032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TownOrCity' and @name = 'TownOrCity']</value>
      <webElementGuid>b49a4fd5-600d-4d75-9d45-87954be7505c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
