<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Building Name_Building</name>
   <tag></tag>
   <elementGuidId>f02a29b6-cb07-4461-bb40-ccbffa231c2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Building</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Building']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af0aa7b4-b719-4461-a487-ade800e04ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-controlPrimary select-boxPrimary ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c3b12352-2116-4bb1-bcc7-a10b4707826d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>building</value>
      <webElementGuid>0ce7daf3-dcfa-40af-9639-15372ee6626d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Building</value>
      <webElementGuid>5c07577c-4c2a-425c-a656-ae176d525c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Building</value>
      <webElementGuid>f4476ff6-ad60-495a-82ba-a3ce9cfe93dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>175573f5-d859-47f2-a6e3-76613d6236cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Building&quot;)</value>
      <webElementGuid>7493ed1c-bcd2-4e0e-9c3e-f234dda1e59f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Building']</value>
      <webElementGuid>f05d07d7-2631-4749-b638-c09ab4f08229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/locationlist/div/div[5]/div[2]/locationdetail/div/form/div[4]/input</value>
      <webElementGuid>8df4f6f5-7f7d-486a-9ac9-fe384f9de16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>172d9528-1ea5-4d00-aa1f-cc203c24d53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Building' and @name = 'Building' and @type = 'text']</value>
      <webElementGuid>3ec28b7d-3dd3-4094-81f8-1b2d6cbb91db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
