<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Site_LocationName</name>
   <tag></tag>
   <elementGuidId>e1d16226-23d3-4be2-b5b0-f60e5ab7c0c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LocationName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LocationName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aed21ecc-9b15-4c03-9bd4-121732e779d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-controlPrimary select-boxPrimary ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>742eee4e-5917-4554-8bca-bcf378245224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>locationName</value>
      <webElementGuid>0f0796ad-c612-4b96-a111-52ceff9fc92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LocationName</value>
      <webElementGuid>cc4303e1-5141-439f-9c7a-5e3060380808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LocationName</value>
      <webElementGuid>023e80bc-5a19-4610-a7dc-91eb4ec4b6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3bcc5783-2369-4eae-8846-8d7b75fb7d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LocationName&quot;)</value>
      <webElementGuid>77f28ab9-2d30-4e2a-abd1-74a80f039a53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LocationName']</value>
      <webElementGuid>c2353de8-0867-4ea8-864c-2d2c9bac54c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/locationlist/div/div[5]/div[2]/locationdetail/div/form/div[3]/input</value>
      <webElementGuid>74b690dc-bf85-483f-a69f-e25195fec187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/input</value>
      <webElementGuid>8ae9fe95-7f07-4e7d-9491-e23244aab154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LocationName' and @name = 'LocationName' and @type = 'text']</value>
      <webElementGuid>42812454-6feb-425b-b9cd-f7a7c3f0b447</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
