<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>room_button_Save</name>
   <tag></tag>
   <elementGuidId>94711127-a498-4f7e-bf35-c00e9ab30c99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.save-and-cancel-buttons-container > #saveBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='saveBtn'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c92db63-ba4f-4444-87d2-365c814949a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>655e3a10-1378-4535-836b-57a20cb3f960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saveBtn</value>
      <webElementGuid>87d0c6ba-64d2-487a-ae8f-662848fab0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>605632bf-8f66-4454-886f-d79aaaf73a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>adab26bc-fd6a-44ee-ba12-728a8a02eaad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)/rooms[1]/div[@class=&quot;pageAnimation&quot;]/div[2]/div[4]/roomdetail[1]/div[@class=&quot;pageAnimation&quot;]/form[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;save-and-cancel-buttons-container&quot;]/button[@id=&quot;saveBtn&quot;]</value>
      <webElementGuid>63723e61-faf1-4818-afb3-9bda6dcef86f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='saveBtn'])[2]</value>
      <webElementGuid>9201af05-5f07-41c8-b1da-3e75f86e5d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/rooms/div/div[2]/div[4]/roomdetail/div/form/div[5]/button[2]</value>
      <webElementGuid>45b94888-58d0-4d5d-b808-5f43fb667e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::button[1]</value>
      <webElementGuid>5da01c17-a35b-47e3-b88b-ee2316c3b653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Screen Theme'])[1]/following::button[2]</value>
      <webElementGuid>132c8d5c-2030-46ba-b8ca-ae1d99305700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::button[1]</value>
      <webElementGuid>84c097d4-1f9a-4018-983f-f820b74feffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unable to proceed!'])[1]/preceding::button[2]</value>
      <webElementGuid>c24b90a7-a39e-4b7d-95de-7c832a8f8212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button[2]</value>
      <webElementGuid>ec788cb6-9fe8-4098-b6b5-2949127591d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'saveBtn' and @type = 'submit' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>7622a8a7-ee99-4430-9949-c17932dab408</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
