<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1</name>
   <tag></tag>
   <elementGuidId>4c29bbc1-3148-4a89-a392-59ddc55e6f27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.active > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content-wrapper']/users/div/div[4]/nav/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0573accc-81bb-4726-b094-a9bef5897dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>918adcf2-68f5-4d3e-aa8b-2962e83cac1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)/users[1]/div[@class=&quot;pageAnimation&quot;]/div[@class=&quot;text-center&quot;]/nav[1]/ul[@class=&quot;pagination&quot;]/li[@class=&quot;active&quot;]/a[1]</value>
      <webElementGuid>40bf33d3-bce2-4cfb-af77-32a5127d9a9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/users/div/div[4]/nav/ul/li[2]/a</value>
      <webElementGuid>243fb2dc-0e2f-48ad-afd0-74fbe17071e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'1')]</value>
      <webElementGuid>5eff26c2-d141-4b0f-80ae-ad2a591c6aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[10]/following::a[2]</value>
      <webElementGuid>7a689c66-75a8-4c56-a54e-fc642650f04a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[8]/following::a[2]</value>
      <webElementGuid>3afc4bda-fa75-487b-a4b6-7fa3e5e8b215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>be259f72-79ec-4539-a53f-b1c835ce9919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/nav/ul/li[2]/a</value>
      <webElementGuid>dcfa0ffd-9aa2-4413-9dd7-1ad0b5000dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '1' or . = '1')]</value>
      <webElementGuid>8652ffbc-7290-4249-9c19-7ba9b01a7a88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
