<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Users_icon-connect-users</name>
   <tag></tag>
   <elementGuidId>310a8a38-6f04-471f-8e4e-6969ba355161</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.icon-connect-users</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='users']/div/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>d970ebf5-834b-4589-950e-a8cafe7752eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-connect-users</value>
      <webElementGuid>1b73683c-30cc-4c48-a940-b4c9eb38aa34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;users&quot;)/div[1]/em[@class=&quot;icon-connect-users&quot;]</value>
      <webElementGuid>58057c00-cb12-464e-b90a-cbb5b16e1919</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='users']/div/em</value>
      <webElementGuid>6c311e7d-e4e8-4c1a-870b-dc3b6a04dfa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div/em</value>
      <webElementGuid>271f99a0-9d04-4171-abd1-cab5f48e58f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
