<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_niharikatesting4194katalon.com</name>
   <tag></tag>
   <elementGuidId>09f0ea91-ca70-4e7d-9269-899290317674</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='userList']/tbody/tr[3]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d52e614f-6dc6-470b-9bb5-2ec649fb292d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>niharikatesting4194@katalon.com</value>
      <webElementGuid>da237c2c-92da-4f40-a1f7-d6268445749c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userList&quot;)/tbody[1]/tr[3]/td[3]</value>
      <webElementGuid>c3e47c7a-de0c-498c-9672-45afe622d2b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='userList']/tbody/tr[3]/td[3]</value>
      <webElementGuid>b86d417d-2026-40e4-81d1-798cc16c0423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='niharika4194'])[1]/following::td[1]</value>
      <webElementGuid>3c1efa84-c734-4c68-8c5f-9cdc9ec769d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon'])[3]/following::td[2]</value>
      <webElementGuid>5e657fd8-071e-4cee-87e3-f9e2d75c734f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[2]/preceding::td[1]</value>
      <webElementGuid>96a14931-ba33-4841-9dd8-95e0a8ccd901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[3]/preceding::td[2]</value>
      <webElementGuid>6d6c503c-98c2-4a46-95e7-e32ca268483a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='niharikatesting4194@katalon.com']/parent::*</value>
      <webElementGuid>672dbef4-e41a-417a-b4c7-ecf39f800fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]</value>
      <webElementGuid>e1a1ebec-f84e-4047-a704-c8c4d979f4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'niharikatesting4194@katalon.com' or . = 'niharikatesting4194@katalon.com')]</value>
      <webElementGuid>b50ac3ab-07c1-42a8-9490-371f45939cab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
