<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add new theme</name>
   <tag></tag>
   <elementGuidId>50f0c4d6-41b5-4e1d-8b6f-8da4457b2f89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addNewScreenTheme</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addNewScreenTheme']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>67411cd0-fb0b-41bb-8ddc-3ce2ed91faf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-button btn btn-default pull-right</value>
      <webElementGuid>3f071a50-3b1a-4117-a7a2-0e9c8c2b8d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addNewScreenTheme</value>
      <webElementGuid>0b8b9119-4723-479c-81d8-443191e1155c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add new</value>
      <webElementGuid>6b921b20-d41f-4c6e-b237-06bcd6a05bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add new theme</value>
      <webElementGuid>295012d6-ea78-46fe-b302-b8738af24dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)/screenthemes[1]/div[@class=&quot;pageAnimation&quot;]/div[@class=&quot;content-heading&quot;]/h1[1]/div[1]/a[@id=&quot;addNewScreenTheme&quot;]</value>
      <webElementGuid>4ff9127a-1d55-4182-8c61-bcccfbebd3a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addNewScreenTheme']</value>
      <webElementGuid>94aecdea-71ea-47ed-98b9-00cdae3d8263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/screenthemes/div/div/h1/div/a</value>
      <webElementGuid>71785dac-544b-4bc3-89f4-0d33e6f5b281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add new theme')]</value>
      <webElementGuid>3b68c4a1-7048-425b-bc33-d919fedef60c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/following::a[2]</value>
      <webElementGuid>0015da41-05c9-4d43-b435-c534be031fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customise the look of your Room screens'])[1]/preceding::a[1]</value>
      <webElementGuid>1ea358a0-2297-4166-ab3a-3a3f2e3ecba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter themes'])[1]/preceding::a[1]</value>
      <webElementGuid>375ed773-60e3-46fb-bd85-71a3a18b4ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add new theme']/parent::*</value>
      <webElementGuid>271812a2-f1b1-4847-810f-24cdd7cde39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/div/a</value>
      <webElementGuid>e99a4036-2a29-4c06-a304-d42729a807e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'addNewScreenTheme' and (text() = 'Add new theme' or . = 'Add new theme')]</value>
      <webElementGuid>c6405f42-85fa-43e5-9b88-5ba8a74c2385</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
