<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Choose a theme name_panel-body</name>
   <tag></tag>
   <elementGuidId>f42acc5b-3274-44c5-a676-6eef3ca233f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accordion > div.panel.panel-default > div.panel-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordion']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dac13536-388e-4bf6-8b03-4004612e74ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-body</value>
      <webElementGuid>a23362f3-3937-4812-a1d4-3fe47b04e97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]</value>
      <webElementGuid>d32a23e6-7232-4285-8cf8-747871d4a0f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div/div[2]</value>
      <webElementGuid>30fec805-ea3e-4a12-9381-be6693325087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a theme name'])[1]/following::div[1]</value>
      <webElementGuid>39112fe8-4136-4163-b43f-165af502846e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customise the look of your Room screens'])[1]/following::div[13]</value>
      <webElementGuid>0fe3a940-70d0-49c0-bc2e-3e4b9cc736ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select country , location &amp; building'])[1]/preceding::div[2]</value>
      <webElementGuid>8b340c82-5ddc-49db-bfe4-74dd981e49ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/preceding::div[3]</value>
      <webElementGuid>bab942f6-ff04-490c-9a87-7c876268d754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>596a60fc-7d69-4526-95b9-5deea54b3749</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
