<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Screen Themes_icon-connect-themes</name>
   <tag></tag>
   <elementGuidId>aa1004b1-3271-4722-a4a8-c2a4644a0049</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.icon-connect-themes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='themes']/div/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>78b163d5-9131-4ab0-b576-188ca553a696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-connect-themes</value>
      <webElementGuid>2127f3c9-79d6-4897-b8a7-bf5f91f3a8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;themes&quot;)/div[1]/em[@class=&quot;icon-connect-themes&quot;]</value>
      <webElementGuid>6a6914f3-c3c4-4deb-9516-566cef07609f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='themes']/div/em</value>
      <webElementGuid>5c9b49f8-d653-446b-a20d-3a33632e4bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/div/em</value>
      <webElementGuid>39452a2c-4849-4d7d-9f16-763c75dd98b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
