<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose a theme name_themeName</name>
   <tag></tag>
   <elementGuidId>0994395d-8348-4846-aee8-073599736013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#themeName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='themeName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef9a84f8-047c-4421-a1ce-93c2ca9e9d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-dirty ng-invalid</value>
      <webElementGuid>ac72d98c-50f9-4132-82cf-95c68a375a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>themeName</value>
      <webElementGuid>d985bc56-bdd4-49b8-8792-0a56147c4693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>themeName</value>
      <webElementGuid>2e99754f-ff6a-4d32-ab61-4d23762c5cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>themeName</value>
      <webElementGuid>5fd9ca8a-19a4-48c8-86e1-d45723f386e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;themeName&quot;)</value>
      <webElementGuid>62724eac-ef4d-429b-b1d3-e75e9e1cb79a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='themeName']</value>
      <webElementGuid>e0ac0acc-9243-4615-803f-7cca3802ca33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div/div[2]/div/input</value>
      <webElementGuid>d9da59b3-04db-4c2a-b7c1-4b22ffdfd208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/input</value>
      <webElementGuid>1262d339-d28b-4066-889c-6fc255fc1576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'themeName' and @name = 'themeName']</value>
      <webElementGuid>0bdbc36a-078c-4741-8490-12f3d73acb86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
