<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Users_icon-connect-users</name>
   <tag></tag>
   <elementGuidId>8c962475-1523-445a-aadc-55e8185cbe8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.icon-connect-users</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='users']/div/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>b931443b-b8fa-45e8-9470-3aaa1a56ec60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-connect-users</value>
      <webElementGuid>efa31553-a4f3-416d-8608-7a3d72d3edd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;users&quot;)/div[1]/em[@class=&quot;icon-connect-users&quot;]</value>
      <webElementGuid>4697c9fb-6d4e-442e-bb48-9eea1b695d60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='users']/div/em</value>
      <webElementGuid>5135af9b-da39-4f2e-8521-f981cc8597c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div/em</value>
      <webElementGuid>7fda7b2c-e82b-4d57-bedb-4c378ec7fe3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
