<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__lnr lnr-trash</name>
   <tag></tag>
   <elementGuidId>ed7bb6ba-a7ee-4f14-ab08-6aaf1d10b2f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content-wrapper']/useraccess/div/div[2]/div/form/div[2]/div[2]/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>58264ccf-6be3-443a-bc9c-479171806c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>74b7d172-692b-478b-9ae5-9b1f8cf531d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lnr lnr-trash</value>
      <webElementGuid>5537c1b5-74db-47c9-8fff-e10c386c55e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)/useraccess[1]/div[@class=&quot;pageAnimation&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/form[@class=&quot;ng-dirty ng-valid ng-touched&quot;]/div[@class=&quot;row form-inline domain-row&quot;]/div[@class=&quot;col-xs-1&quot;]/div[1]/button[@class=&quot;btn btn-delete&quot;]/i[@class=&quot;lnr lnr-trash&quot;]</value>
      <webElementGuid>5afaea39-c9ae-4aa5-baf9-8e61b2f53957</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/useraccess/div/div[2]/div/form/div[2]/div[2]/div/button/i</value>
      <webElementGuid>8a5241bf-8f3c-414e-8115-ca149b845c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button/i</value>
      <webElementGuid>23cfe837-c65e-437c-8d51-cd2cedac539d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
