<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add user</name>
   <tag></tag>
   <elementGuidId>1bd9db34-7a7f-48cb-990c-e8a6dd0f58b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addNewUser</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addNewUser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>13da6e01-d4b2-429d-a07b-c01d6e6af076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-button btn btn-default pull-right</value>
      <webElementGuid>6393326f-2519-4648-b894-3d8acce2326f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addNewUser</value>
      <webElementGuid>227c2142-a33f-4e1a-87c3-f1085c06d02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add new</value>
      <webElementGuid>bad72b0d-ffff-405e-9c65-8f00d6c322b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add user</value>
      <webElementGuid>e1431a3d-2f63-4f42-8b1e-584ebe242142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addNewUser&quot;)</value>
      <webElementGuid>3e444769-72a8-48a9-9d43-dca5a17f259d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addNewUser']</value>
      <webElementGuid>4906ecb2-7e3e-4960-839f-2c133d27f66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/users/div/div[2]/div/div/div[2]/a[2]</value>
      <webElementGuid>c0b6dd3c-5349-4413-aa9d-58aa5ad2d585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add user')]</value>
      <webElementGuid>a7ed735d-2616-455a-b281-f563bad0e628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download user data'])[1]/following::a[1]</value>
      <webElementGuid>24c84399-c7ae-4e97-bac8-753184fb38c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download sample CSV file'])[1]/following::a[2]</value>
      <webElementGuid>af432ea8-3d80-43ea-beab-6decf197f55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulk upload'])[1]/preceding::a[1]</value>
      <webElementGuid>aab3f91a-150c-4c38-b61f-a068a13d280b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show'])[1]/preceding::a[2]</value>
      <webElementGuid>518d3e54-cfeb-4efb-9401-55ee89b37848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add user']/parent::*</value>
      <webElementGuid>38e9e4d2-479d-47ed-a4d1-f5b3e127438f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>69b2069d-8446-4ed4-9ac1-8c0391b832e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'addNewUser' and (text() = 'Add user' or . = 'Add user')]</value>
      <webElementGuid>a5aeb700-8bcc-4d4b-a9f4-a90df8592c71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
