<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>590fc410-2676-4109-90a3-00498c98b9d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signoutPrimary > a > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='signoutPrimary']/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cbb1aba2-52a8-4517-b81f-08bfe8b64fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signoutPrimary&quot;)/a[1]/div[1]</value>
      <webElementGuid>abac5f50-5942-4587-9047-7c08e6000571</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signoutPrimary']/a/div</value>
      <webElementGuid>018cbe5b-ef93-4b7b-9d3e-b1167865d8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/preceding::div[2]</value>
      <webElementGuid>5d93dac3-d92c-473f-95a6-1267a39bf095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office 365'])[1]/preceding::div[5]</value>
      <webElementGuid>3b6c183d-040a-44c6-8b3a-a3d67177c13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/div</value>
      <webElementGuid>bd0c52a3-32a8-448a-8882-6f5491362125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
