<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Users_icon-connect-users</name>
   <tag></tag>
   <elementGuidId>28c654dd-abaf-43c8-91da-aa78d2b99495</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.icon-connect-users</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='users']/div/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>a1cdb581-fcd1-425f-9e79-8c70cdb874c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-connect-users</value>
      <webElementGuid>cefc96d0-2d72-4d7b-8446-bf152341b499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;users&quot;)/div[1]/em[@class=&quot;icon-connect-users&quot;]</value>
      <webElementGuid>200e5fb9-831d-40f4-aa6d-bb3d7ec70937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='users']/div/em</value>
      <webElementGuid>f749501c-f6d4-45dc-b4f7-07f1311b0e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div/em</value>
      <webElementGuid>44a7907c-05dd-4c95-afd0-499248f7acfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
