<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile phone number_mobilePhoneNumber</name>
   <tag></tag>
   <elementGuidId>e763df46-9ba1-42bb-95a7-185c779d06c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobilePhoneNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mobilePhoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf9ba155-7e27-47b0-ab9b-0dc44917437b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>4bdf3871-c02e-4820-ae7e-fe370aa6a68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>mobilePhoneNumber</value>
      <webElementGuid>9b83a95e-6977-4247-b6a4-294e090f5b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobilePhoneNumber</value>
      <webElementGuid>42f2ce65-5db7-44ea-b459-b79cfbe66d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobilePhoneNumber</value>
      <webElementGuid>274a7166-3e8d-4a5d-ac4d-1d6490d2a8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobilePhoneNumber&quot;)</value>
      <webElementGuid>f4e9fede-46a8-4c12-b249-c8a1297c0701</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mobilePhoneNumber']</value>
      <webElementGuid>a31eff5c-c220-4998-868e-6811d90fcc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/users/div/div[5]/div[2]/userdetail/div/form/div[4]/input</value>
      <webElementGuid>6f1a9153-152b-4401-839c-500cafaf5338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>d0d28ff2-3614-49b7-ac23-bd21aa6046f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mobilePhoneNumber' and @name = 'mobilePhoneNumber']</value>
      <webElementGuid>5bbd8a24-b4e4-443c-bf08-2f20242e2d22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
