<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Screen Themes_icon-connect-themes</name>
   <tag></tag>
   <elementGuidId>cd0b33be-840d-400b-8513-10c2599f442a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.icon-connect-themes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='themes']/div/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>00c07454-e491-4cf0-8b4c-10b8e4e29dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-connect-themes</value>
      <webElementGuid>91f7bf2b-bf29-4767-9399-658ca0492b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;themes&quot;)/div[1]/em[@class=&quot;icon-connect-themes&quot;]</value>
      <webElementGuid>f3a82c12-b740-4503-9342-c10e7b07cfaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='themes']/div/em</value>
      <webElementGuid>9b8c87b6-de0b-4eac-be25-d1a9d996329e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/div/em</value>
      <webElementGuid>368814c0-fb42-4fd4-84d9-f308a318a3d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
