<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SET AS DEFAULT_img-responsive</name>
   <tag></tag>
   <elementGuidId>f1ac5976-f749-4aa0-b3fe-c0c08037a4b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content-wrapper']/screenthemes/div/div[3]/div[3]/div[114]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8c9a86a3-fe32-498f-b65c-e10dfd8ed68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>thumbnail</value>
      <webElementGuid>36bd3714-3de4-4a8e-8541-900a87b1e701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>2bf486eb-962f-4c36-908f-41bca50f1a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage-qa.condecodev.com/c1db3746-76f5-4598-9258-e4603554826b/themes/d1221c54-ae15-4418-b96e-6ed1cab89615/thumbnail?sv=2018-03-28&amp;sr=b&amp;sig=gdLJho9G3sYdXClOATm+KWL7yfqYyeMs79oR1LS0TXY%3D&amp;st=2023-03-10T13%3A30%3A48Z&amp;se=2023-03-15T13%3A35%3A48Z&amp;sp=r</value>
      <webElementGuid>93d130ef-0656-4d93-81d5-ed69a108e70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)/screenthemes[1]/div[@class=&quot;pageAnimation&quot;]/div[@class=&quot;panel-default&quot;]/div[@class=&quot;row is-flex&quot;]/div[@class=&quot;col-lg-3 col-padding width-Theme&quot;]/div[@class=&quot;panel panel-default panel-card width-Themes&quot;]/div[@class=&quot;panel-body panel-card-body&quot;]/a[1]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>2e8a92ca-947e-47f8-825b-c98d188ce322</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/screenthemes/div/div[3]/div[3]/div[114]/div/div/a/img</value>
      <webElementGuid>1af6d4dc-7286-4d5f-9e3d-3334bce05d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='thumbnail'])[114]</value>
      <webElementGuid>287e3f7c-b3cf-42da-85b2-a7e8741a6831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[114]/div/div/a/img</value>
      <webElementGuid>a3f28022-c267-4815-b5b9-e3a745e21fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'thumbnail' and @src = 'https://storage-qa.condecodev.com/c1db3746-76f5-4598-9258-e4603554826b/themes/d1221c54-ae15-4418-b96e-6ed1cab89615/thumbnail?sv=2018-03-28&amp;sr=b&amp;sig=gdLJho9G3sYdXClOATm+KWL7yfqYyeMs79oR1LS0TXY%3D&amp;st=2023-03-10T13%3A30%3A48Z&amp;se=2023-03-15T13%3A35%3A48Z&amp;sp=r']</value>
      <webElementGuid>df6f3603-a0c4-423e-afca-6d0ea3f56825</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
