<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose a theme name_themeName</name>
   <tag></tag>
   <elementGuidId>5f59367e-9cad-4781-9f52-db6721e5a8c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#themeName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='themeName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d1e0c98-a5ec-474d-b2a0-107db5ec0584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>d6381f03-fb49-4c37-963a-22a670a89c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>themeName</value>
      <webElementGuid>b68a7726-3e9e-4b55-a46f-3d3e3bf24795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>themeName</value>
      <webElementGuid>c51224b0-18d6-4bc2-88e6-4825c9df0f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>themeName</value>
      <webElementGuid>149cce08-635f-44e3-b650-5e0c5b730bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;themeName&quot;)</value>
      <webElementGuid>9b18ba8e-29ff-48cf-bb9a-d2c733bfd4c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='themeName']</value>
      <webElementGuid>8a1222cc-0afe-4c57-933d-577e91c48749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div/div[2]/div/input</value>
      <webElementGuid>aaf89c60-b420-4120-aa79-99e6ece75942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/input</value>
      <webElementGuid>904abb3b-5f8f-4f7f-ab16-d716f1981f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'themeName' and @name = 'themeName']</value>
      <webElementGuid>69edd862-fa50-4e5a-ba29-c73693416550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
