<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Building Name_Building</name>
   <tag></tag>
   <elementGuidId>0667a583-14e3-470a-8ac7-da28e9bd57b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Building</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Building']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12743d02-18d1-4f0f-b302-9fe69ec4b58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>64f5fc97-8f1b-4f79-8c6d-32abb00e88b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>building</value>
      <webElementGuid>9a293ee7-3529-4da3-a20e-dae924f73dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Building</value>
      <webElementGuid>2cf328dd-89e2-4185-8955-431b9796dab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Building</value>
      <webElementGuid>00451061-faf9-46ba-adb4-b50c42096d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2fd712bd-2865-42a3-aa32-80d9ed859e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Building&quot;)</value>
      <webElementGuid>5f667e8d-63fe-4817-a190-e740a77c9596</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Building']</value>
      <webElementGuid>7b35aa11-5e10-4e28-9059-ef6199a0acdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/locationlist/div/div[5]/div[2]/locationdetail/div/form/div[4]/input</value>
      <webElementGuid>1da3ab35-a49f-4e6c-94dc-339d6477e140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>1bbbfdfe-a032-4e69-ab3a-eb4bc720abe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Building' and @name = 'Building' and @type = 'text']</value>
      <webElementGuid>6fa23c24-cc8e-4621-a074-28d8e7fb2b07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
