<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Town Or City_TownOrCity</name>
   <tag></tag>
   <elementGuidId>03baf78b-d83b-4153-a963-65379ea9386a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TownOrCity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TownOrCity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4cf40f35-3240-4f8b-b5fe-b0fcb6e1348e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>40154376-120d-4387-8797-0214b47d755b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>townOrCity</value>
      <webElementGuid>601f4b84-a6da-43df-adb2-11c152a2a663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TownOrCity</value>
      <webElementGuid>9b4b8e71-2831-4797-bc73-3617209bc3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>towns</value>
      <webElementGuid>2422f6a4-c21c-474b-9487-285ad5945d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TownOrCity</value>
      <webElementGuid>30594311-935e-4917-822b-72f2811907e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TownOrCity&quot;)</value>
      <webElementGuid>4e710b8a-760c-4bbe-bde4-fdf7dbdb020c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TownOrCity']</value>
      <webElementGuid>1dcebd3e-ab7a-44d1-aa26-7648fd9c1ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/locationlist/div/div[5]/div[2]/locationdetail/div/form/div[2]/input</value>
      <webElementGuid>57e4390c-cfd4-47b6-b207-e65d2a3a21f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>7c813d24-8ac0-4fd4-b27d-ec1f4e67ddd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TownOrCity' and @name = 'TownOrCity']</value>
      <webElementGuid>e2fa69ba-d478-484b-9e2e-b7033ae2d738</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
