<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Site_LocationName</name>
   <tag></tag>
   <elementGuidId>ac0ba7a3-a987-4bb8-a726-3d2de1b6deb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LocationName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LocationName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76c76189-8b89-4094-9666-57a9c4e305a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>e0ab6ec7-14f3-4907-ba8a-97c381f2c191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>locationName</value>
      <webElementGuid>af5ab04c-1fd0-4bc9-8898-388ece42fc27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LocationName</value>
      <webElementGuid>535aeca6-7aa7-4cae-a597-ab24b5776dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LocationName</value>
      <webElementGuid>cb60fbe1-dd7f-4e8e-9ed6-3b8d1ecfec1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5eb63c14-3845-4534-ab38-23a3de69674d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LocationName&quot;)</value>
      <webElementGuid>223da63d-76c7-4f13-89c4-91a095b0c873</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LocationName']</value>
      <webElementGuid>e0806df0-049b-401a-80a8-68d0cf68f7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/locationlist/div/div[5]/div[2]/locationdetail/div/form/div[3]/input</value>
      <webElementGuid>c9a666aa-7f71-4cf6-ace5-f2441e26a249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/input</value>
      <webElementGuid>25794251-1063-4041-a321-f49315e70fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LocationName' and @name = 'LocationName' and @type = 'text']</value>
      <webElementGuid>8552348d-511f-4e76-ac0f-2bde278cf1db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
