<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add another</name>
   <tag></tag>
   <elementGuidId>9c0233de-a9a6-47e0-8661-694aeb68f481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addDomainButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addDomainButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e0fc2503-97de-427a-913d-8d2e9f54156c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-domain pull-right </value>
      <webElementGuid>57736f73-d469-4978-adc8-3ebdf98e5b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addDomainButton</value>
      <webElementGuid>4eeb95c0-1a17-4d18-b594-18a47d0dc221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4955596f-c03a-4aaa-80ca-153d33907575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add another</value>
      <webElementGuid>f289a1c1-1ea0-4672-a9d4-e101c9c2e800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addDomainButton&quot;)</value>
      <webElementGuid>92668321-94d3-4dc2-a724-3515c5685783</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addDomainButton']</value>
      <webElementGuid>5e88f86d-b93b-41fa-9e93-589e1676efcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/useraccess/div/div[2]/div/form/div[2]/div/button</value>
      <webElementGuid>9783191d-5a64-4345-8028-7f3319aace4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@'])[1]/following::button[2]</value>
      <webElementGuid>b3efc61c-cfaa-4755-adab-bd9ad9953555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Define who can register as a user'])[1]/following::button[2]</value>
      <webElementGuid>abf51c27-5f25-4a98-889b-de779d2111f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::button[1]</value>
      <webElementGuid>7c1a5a89-aa0b-490b-a8e0-a25cd10fbc72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[2]</value>
      <webElementGuid>9aa96fc4-1b2c-4b37-8be6-75ffbab704b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add another']/parent::*</value>
      <webElementGuid>0fb5cb47-5d1b-4d98-b7bc-6cd3cca0233f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/button</value>
      <webElementGuid>47317f3d-746d-49c5-a4e7-8f63e24257b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'addDomainButton' and @type = 'button' and (text() = 'Add another' or . = 'Add another')]</value>
      <webElementGuid>9237bffd-2265-43b0-8622-8dfebd1e74cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
