<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Users_icon-connect-users</name>
   <tag></tag>
   <elementGuidId>aa1eae71-4661-48bf-b125-b0a508acf87c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.icon-connect-users</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='users']/div/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>d0d536be-9b99-4a77-a36d-5e0409761be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-connect-users</value>
      <webElementGuid>1113fbae-163b-45e8-b805-1aa181cead4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;users&quot;)/div[1]/em[@class=&quot;icon-connect-users&quot;]</value>
      <webElementGuid>3c0a0a08-cb77-427e-9fa0-dcc0d4a7c7ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='users']/div/em</value>
      <webElementGuid>5ce68034-6861-4896-a814-eb7b0013f7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div/em</value>
      <webElementGuid>2f2add32-8a32-4f58-a6e9-b30d44ed23cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
