<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add another</name>
   <tag></tag>
   <elementGuidId>c69b8bc9-4cf6-4bd3-94d7-afc3dad4e6fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addDomainButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addDomainButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a183b5e1-203a-4b11-935d-d2b28d1a9128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-domain pull-right </value>
      <webElementGuid>63f6cb64-2255-4b05-9e14-ba6e92fc661f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addDomainButton</value>
      <webElementGuid>15fdec29-5d2c-4714-a5b9-32c9f2e3e0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59b2b95b-d252-460c-b328-18944b54dadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add another</value>
      <webElementGuid>20eb63ba-75c6-4952-87c4-635e0eae8308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addDomainButton&quot;)</value>
      <webElementGuid>637d1365-ce70-4e86-ad16-3ae944b6bf83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addDomainButton']</value>
      <webElementGuid>bc7ec089-7027-4033-8f5a-e2afd5e7ee06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/useraccess/div/div[2]/div/form/div[2]/div/button</value>
      <webElementGuid>df8c1177-6240-44aa-bfa7-383eeae76bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@'])[1]/following::button[2]</value>
      <webElementGuid>5da924aa-a3c5-4d6b-8518-817774c3caeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Define who can register as a user'])[1]/following::button[2]</value>
      <webElementGuid>8921ebf3-84a4-4f6e-a174-b19d581380cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::button[1]</value>
      <webElementGuid>1ce28ca3-7d2c-450f-b4d8-82997d8ec04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[2]</value>
      <webElementGuid>bca99214-aa55-48f8-9b60-b22e8865f3d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add another']/parent::*</value>
      <webElementGuid>dfc29dab-cc18-49c5-8098-84ae16aaef69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/button</value>
      <webElementGuid>58ea518e-5e61-45d6-8e59-58bc937a56af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'addDomainButton' and @type = 'button' and (text() = 'Add another' or . = 'Add another')]</value>
      <webElementGuid>cb2ef35a-196c-4d95-afbd-384063960ef0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
