<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>49cf5fea-0d8f-48fa-8970-10b593c10c35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signoutPrimary > a > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='signoutPrimary']/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>700df639-3ff8-49e2-a517-13a61c087750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signoutPrimary&quot;)/a[1]/div[1]</value>
      <webElementGuid>01fb234a-c6d7-4af7-a2e1-88350c347f80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signoutPrimary']/a/div</value>
      <webElementGuid>572d785d-5015-4b06-93fd-cf75c3969769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/preceding::div[2]</value>
      <webElementGuid>d0dbab11-87e2-4e6a-b50e-be39b2652eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon exchnage'])[1]/preceding::div[5]</value>
      <webElementGuid>52bbbde7-df6e-4377-9852-0d386ccf18cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/div</value>
      <webElementGuid>0acb7981-fd5b-4288-b98d-4cbb4fb3654c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
