<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add service</name>
   <tag></tag>
   <elementGuidId>39dc25dd-2121-4c56-a73a-a8f683f8ed29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addServiceButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addServiceButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5de5cb42-89a2-4b88-b035-68a9660caff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-button btn btn-default pull-right </value>
      <webElementGuid>c3fa04b5-7bf1-4821-a560-422f30e4ca6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addServiceButton</value>
      <webElementGuid>45d54b5d-cea4-412f-8518-6f9a8e59d06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a798e129-4e9e-4cd1-bc49-a5fd610548fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Add service
                    </value>
      <webElementGuid>8deaaab5-96be-4c90-bcf2-cfe2e86d2811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addServiceButton&quot;)</value>
      <webElementGuid>94f3531d-d571-481c-9d6f-4a564a309941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addServiceButton']</value>
      <webElementGuid>b8017f41-ece2-48ec-ad62-1701c143b407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/calendarsettings/div/div[2]/div/div/div/button</value>
      <webElementGuid>33cd0d3e-aadb-487d-9a85-c05b37c78c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage your calendar service(s)'])[1]/following::button[1]</value>
      <webElementGuid>2ff4a1e5-3409-43c8-8b75-326e35c52511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TYPE'])[1]/preceding::button[1]</value>
      <webElementGuid>14e1f00d-6578-4d81-a700-592f940c71ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NAME'])[1]/preceding::button[1]</value>
      <webElementGuid>0097c140-c522-4780-a532-6fecd4d8949f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add service']/parent::*</value>
      <webElementGuid>be273f74-958c-4383-94a8-8cf6cfa91f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button</value>
      <webElementGuid>e1b56654-b7f4-4ea0-8760-e5b98c1d1918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'addServiceButton' and @type = 'button' and (text() = '
                        Add service
                    ' or . = '
                        Add service
                    ')]</value>
      <webElementGuid>9c5bb0d5-0ee9-42fa-a9b3-180ccadfa34c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
