<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>26b488eb-6273-42af-908d-90a58d5c5724</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calendar > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='calendar']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a92ba441-3d35-432b-9208-ff023899fbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendar&quot;)/div[1]</value>
      <webElementGuid>48abdf62-01c9-43ab-88bb-d6bd9848163d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='calendar']/div</value>
      <webElementGuid>3df513c6-2e1a-482a-86cf-0de05ce0318c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calendar Settings'])[1]/preceding::div[2]</value>
      <webElementGuid>59967ca4-0336-45aa-a8ea-d0fdae426d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office 365'])[1]/preceding::div[10]</value>
      <webElementGuid>2219aee6-0a75-445d-92d9-9a4830cd85f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div</value>
      <webElementGuid>0f1e5dc3-4a35-4fc8-a99f-24db527cd04d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
