<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1</name>
   <tag></tag>
   <elementGuidId>d3ed8a0c-2f0a-44d0-80ed-608dd42ac85e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signoutPrimary > a > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='signoutPrimary']/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3637e1f0-fc84-4a53-b083-cee97313224c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signoutPrimary&quot;)/a[1]/div[1]</value>
      <webElementGuid>eeab9673-b42f-4778-9fa0-b756e1e62621</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signoutPrimary']/a/div</value>
      <webElementGuid>a9bf6ecd-5a7e-46eb-a6d5-14ba6ab07f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/preceding::div[2]</value>
      <webElementGuid>8694508c-90d2-4459-9e29-8defb0832553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office 365'])[1]/preceding::div[5]</value>
      <webElementGuid>57c70af2-a1ce-4c37-bc58-6b8378496dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/div</value>
      <webElementGuid>0f26a91d-cfd9-478f-8e39-d6d798e7278e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
