<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CLIENT ID_clientId</name>
   <tag></tag>
   <elementGuidId>16df4dcd-93bb-4592-88a4-6e44d60df198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clientId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clientId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f571455b-30a7-4b62-bd41-8f219a2e0835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>8e6e6687-f2b4-480a-a0ed-ac88ec2821cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>clientId</value>
      <webElementGuid>7a90ef8c-acf9-4354-a299-3e6f62e13b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clientId</value>
      <webElementGuid>ce1c15ea-b0fb-437e-9a77-10ffa46a591a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>clientId</value>
      <webElementGuid>aada7ffe-f6dc-4787-ae40-29f9272d6920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientId&quot;)</value>
      <webElementGuid>a8c422e6-de65-4c63-8ff2-09e58b2a6ce2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clientId']</value>
      <webElementGuid>74272af7-da70-4924-a645-b6d93acdb543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/calendarsettings/div/div[4]/div[2]/calendarsettingsdetail/div/div/enterprisedetail/div/form/div[2]/div/div/input</value>
      <webElementGuid>37b59f58-f0c2-4da8-a224-888adc94bdca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>58b49182-991a-470a-b5a5-bb886306b5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'clientId' and @name = 'clientId']</value>
      <webElementGuid>9c6471b8-8e8c-4956-9422-176aa46873e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
