<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CLIENT SECRET_clientSecret</name>
   <tag></tag>
   <elementGuidId>c602aec9-1104-41e4-9b84-4a600d45adb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clientSecret</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clientSecret']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55b53aa6-539c-4340-bf1c-6a9546520d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>3b2527e5-5a1b-4a67-8a91-d07831a2bdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>clientSecret</value>
      <webElementGuid>90141661-3fa8-45dc-8f5a-f583ccb624d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clientSecret</value>
      <webElementGuid>0d84e72f-63db-4c49-97bf-e03d461aef0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>clientSecret</value>
      <webElementGuid>dbbd5d65-892b-48dd-ab59-a62f92f57b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientSecret&quot;)</value>
      <webElementGuid>c4e973a4-bcab-4e44-b8ca-50dcc549e382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clientSecret']</value>
      <webElementGuid>87614692-4100-47e9-9452-c55ed0ccb619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/calendarsettings/div/div[4]/div[2]/calendarsettingsdetail/div/div/enterprisedetail/div/form/div[2]/div[2]/div/input</value>
      <webElementGuid>0ab66965-bbd6-4f71-ae8e-b9e3ab21331b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>b6e10379-e2b5-4d54-bdf3-454551e78dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'clientSecret' and @name = 'clientSecret']</value>
      <webElementGuid>16041348-366d-4541-9c49-180cb7e6dec2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
