<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Calendar service successfully set to default</name>
   <tag></tag>
   <elementGuidId>3b240540-ee32-41b9-9381-4f63dfe6f3d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.toast-message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-container']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c530ed39-fed7-4117-9017-591703ce80d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toast-message</value>
      <webElementGuid>9d407f93-1a17-4f0b-a515-fa9df81491b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Calendar service successfully set to default</value>
      <webElementGuid>6b2ce0eb-e9a9-488e-a9ec-975a2f883e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-container&quot;)/div[@class=&quot;toast toast-success&quot;]/div[@class=&quot;toast-message&quot;]</value>
      <webElementGuid>b2b507c4-76b8-44ed-9f1e-ed8a7c0d3811</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div/div</value>
      <webElementGuid>8ea82801-2636-4c04-92b8-cb08c00f8516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/following::div[1]</value>
      <webElementGuid>ee2919fc-7303-4a0f-96a1-b276b412b61d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::div[6]</value>
      <webElementGuid>9f6e72eb-57b3-41f2-86fd-ee382df98193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Calendar service successfully set to default']/parent::*</value>
      <webElementGuid>7acb767d-b523-4add-8fdc-642bdea1d3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>257c7cac-8562-4cf4-b5f0-6ef86faeb063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Calendar service successfully set to default' or . = 'Calendar service successfully set to default')]</value>
      <webElementGuid>f7cddd9b-4dea-4a70-b73d-2d6e790061e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
