<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Calendar Settings_icon-connect-calendar</name>
   <tag></tag>
   <elementGuidId>92af03dd-488c-422c-8c4a-24d7eef00528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.icon-connect-calendar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='calendar']/div/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>e501dbaf-0aa8-41e2-b664-e79ae3ccd209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-connect-calendar</value>
      <webElementGuid>1db44604-59ca-45b0-9368-576eb1323e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendar&quot;)/div[1]/em[@class=&quot;icon-connect-calendar&quot;]</value>
      <webElementGuid>f2cd3637-d684-4d1b-bfb4-b1cacb489426</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='calendar']/div/em</value>
      <webElementGuid>5c416843-b794-4756-be31-0abaa35db2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/em</value>
      <webElementGuid>38157ab3-5807-4b33-ade7-cad806de7ee6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
