<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_OAuth</name>
   <tag></tag>
   <elementGuidId>f98bc45b-f421-4b41-8689-8832c4fb0f63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content-wrapper']/calendarsettings/div/div[4]/div[2]/calendarsettingsdetail/div/div/exchangedetail/div/form/div[3]/div[3]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>1c5fb941-84b0-414e-8317-1d13f9facce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>authOAuth</value>
      <webElementGuid>799600d4-f685-4c09-8b8c-04aabaa41580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OAuth</value>
      <webElementGuid>c616a471-555c-409d-944c-8bd035f301d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)/calendarsettings[1]/div[@class=&quot;pageAnimation&quot;]/div[@class=&quot;panel panel-default accountDetail&quot;]/div[@class=&quot;panel-body&quot;]/calendarsettingsdetail[1]/div[@class=&quot;pageAnimation&quot;]/div[1]/exchangedetail[1]/div[@class=&quot;pageAnimation&quot;]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;custom-radio inline-check&quot;]/label[1]</value>
      <webElementGuid>049747c7-9f73-4d8d-9d8d-74809dbb826c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/calendarsettings/div/div[4]/div[2]/calendarsettingsdetail/div/div/exchangedetail/div/form/div[3]/div[3]/label</value>
      <webElementGuid>632bddb6-d51d-45df-b743-10321c3b370f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NTLM'])[1]/following::label[1]</value>
      <webElementGuid>cc534c3e-6a1d-48eb-8e83-6a7e8a25d126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic/Negotiate'])[1]/following::label[2]</value>
      <webElementGuid>f9550f9e-c38d-4db6-9769-820572590886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OAuth authentication must be selected if connecting to Microsoft 365.'])[1]/preceding::label[1]</value>
      <webElementGuid>1f4f3213-be4c-493b-8ac6-9993106f5032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NTLM or Basic/Negotiate must only be set for on-premise Exchange instances.'])[1]/preceding::label[1]</value>
      <webElementGuid>b65f9258-d6a6-4902-833d-80d90970d129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OAuth']/parent::*</value>
      <webElementGuid>a591834b-bec7-47ff-af56-56c6b9074b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/label</value>
      <webElementGuid>f949f06f-3a20-499c-92e5-771c11555927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'OAuth' or . = 'OAuth')]</value>
      <webElementGuid>d02c7d46-8e30-4d18-9bf7-fdf7b06e5be1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
