<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Room Mailbox_mailbox</name>
   <tag></tag>
   <elementGuidId>e00b1c9d-caa5-4c12-8a40-06c4b5b3aad2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mailbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mailbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94147059-29c7-412b-bab9-9e21f6ad2d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>be038fd8-8599-488e-bd87-ef94f25d4a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>mailbox</value>
      <webElementGuid>6a0aae31-31f5-46ec-aafc-66b60dacb85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mailbox</value>
      <webElementGuid>2269a910-29e6-4964-863d-a0ca95328d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mailbox</value>
      <webElementGuid>c6a47493-45e2-4f72-96f8-fbf7681e87a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter the mailbox details.</value>
      <webElementGuid>aaea974e-c4e4-4586-badf-ced67ae41876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mailbox&quot;)</value>
      <webElementGuid>e3bb4eec-4f90-40ab-a64b-58d3c27d5233</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mailbox']</value>
      <webElementGuid>440edd88-a8ea-4ddf-aaaa-cb860d1b821b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/rooms/div/div[2]/div[4]/roomdetail/div/form/div[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>550d4fdb-a859-4c23-abc8-a145e4eb2004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>23f517b5-972f-4777-89bf-2ffaf083f05d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mailbox' and @name = 'mailbox' and @placeholder = 'Please enter the mailbox details.']</value>
      <webElementGuid>5ef5c637-dc85-4d51-a751-ef4dbb24b9cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
